name: plasticnet
channels:
  - conda-forge
dependencies:
  - python=3.6
  - codecov
  - conda-build
  - coverage
  - ipython
  - numba
  - numpy
  - pytest
  - pytest-cov
  - scikit-learn
  - sphinx
  - sphinx_rtd_theme
  - pre_commit
