name: plasticnet
channels:
  - conda-forge
dependencies:
  - python=3.6
  - codecov
  - coverage
  - ipython
  - numba
  - numpy
  - pip
  - pytest
  - scikit-learn
  - sphinx
  - sphinx_rtd_theme
  - pre_commit
