language: python
python:
  - '3.6'
cache: pip
install:
  - pip install pytest numpy numba networkx
  - pip install -e .

script:
- py.test --pyargs plastic_net --cov-report term-missing --cov=plastic_net

